### ISSUE TITLE
wrong command in VSCode marketplace

### ISSUE THREAD

**Issue by NicholasAntidormi** [vrjuliao/sml-vscode-extension#4]
here https://marketplace.visualstudio.com/items?itemName=vrjuliao.sml-environment `Ctrl+Shift+Enter` should be `Ctrl+Enter` and `Cmd+Enter` for mac

**Comment by vrjuliao** [comment]
Hi @NicholasAntidormi we've fixed it. We will release a new version in VSCode marketplace in few days.
Thank you so much.
