### ISSUE TITLE
Change interpreter to SOML

### ISSUE THREAD

**Issue by RanderGabriel** [vrjuliao/sml-vscode-extension#9]
At first, i would like to say that this extension is awesome! Great job here!

I am opening this issue more as a suggestion than as a issue. I have found another interpreter on NPM, that i think could be added as a dependency on the package.json file, making the library work out of the box whitout depending on the interpreter being installed or not on the user's machine.

This is the link to the library:
https://www.npmjs.com/package/@sosml/interpreter

Is that a good suggestion? It would make the extension bigger, but would also make installation easier. There is a tradeoff here.

I have not tested the library, but i really think it could work.

If you think that it doesn't make sense for the extension, feel free to close this issue, but if you think that it is a good idea, let me know please, and i can contribute with that implementation

**Comment by vrjuliao** [comment]
Hi @RanderGabriel, thank you so much.

About your suggestion, currently it there already exists an extension that uses the SOSML. [See here](https://marketplace.visualstudio.com/items?itemName=bmo-at.vscode-sosml).

But I'm thinking a way to install the interpreter at the same time to the extension. I also have felt the same think about the necessity to install the interpreter separately. Thank you so much again!
